name: Build Assets

on:
  push:
    branches:
      - master
      - new_workflow
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
  pull_request:
    branches:
      - master
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build-builder:
    name: Build Assets builder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dev Dependencies
        run: npm install --save-dev

      - name: Build Project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  build-assets:
    name: Build Assets
    runs-on: ubuntu-latest
    needs: build-builder

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Install Dependencies
        run: npm install

      - name: Start Builder
        run: npm run start

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: assets-dist/

  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    needs: build-assets

    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: assets-dist/

      - name: Upload files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          aws configure set region auto
          aws s3 sync --endpoint-url ${{ secrets.R2_ENDPOINT }} assets-dist/ s3://cat-activity