name: Build Assets

on:
  push:
    branches:
      - master
      - new_workflow
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
  pull_request:
    branches:
      - master
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build-builder:
    name: Build Assets builder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dev Dependencies
        run: npm install --save-dev

      - name: Build Project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  build-assets:
    name: Build Assets
    runs-on: ubuntu-latest
    needs: build-builder

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Install Dependencies
        run: npm install

      - name: Start Builder
        run: npm run start

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: assets-dist/

  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    needs: build-assets

    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: assets-dist/

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          r2-bucket: cat-activity
          source-dir: assets-dist/
          destination-dir: ./