name: Build Assets

on:
  push:
    branches:
      - master
      - new_workflow
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
  pull_request:
    branches:
      - master
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build-builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dev Dependencies
        run: npm install --save-dev

      - name: Build Project
        run: npm run build

  build-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Start Builder
        run: npm run start

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./.builder-tmp
  deploy: