name: Publish Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: sudo chmod +x gradlew

      - name: Create token directory
        run: mkdir -p ./token

      - name: Create and write to chain.crt file
        run: echo "${{ secrets.CHAIN_CRT_CONTENTS }}" | base64 --decode > ./token/chain.crt

      - name: Create and write to private.pem file
        run: echo "${{ secrets.PRIVATE_PEM_CONTENTS }}" | base64 --decode > ./token/private.pem

      - name: Build plugin
        run: ./gradlew buildPlugin
        env:
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Sign plugin
        run: ./gradlew signPlugin
        env:
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Publish plugin
        run: ./gradlew publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
